### ISSUE TITLE
Online demo not working

### ISSUE THREAD

**Issue by glabmoris** [ESTOS/gowebrtc.js#1]
Hi, I'm looking at the different WebRTC/XMPP frameworks out there, and a simplewebrtc derivative that uses XMPP under the hood is a perfect fit. However, the online demo doesn't work. Can I expect the solution to work with my XMPP/BOSH setup or is it still a work in progress?

Thanks

**Comment by fippo** [comment]
Indeed... it doesn't show the video on the caller side. I'll see if I can fix it.

I would however recommend using stanza.io and jingle.js (both on https://github.com/otalk/) instead of strophe.

**Comment by fippo** [comment]
should work again.

**Comment by glabmoris** [comment]
Thanks! I've taken a look at stanza.io, but adding a dependency on Node.js makes the whole idea fall apart since it has to be integrated with an existing webapp and XMPP server (which is integrated to said webapp). Maybe something like strophe.jingle or the like would do the trick.

Thank you for your time and consideration :)

**Comment by fippo** [comment]
oh, stanza requires nodejs only for building. Check https://github.com/legastero/jingle-interop-demos/tree/gh-pages/stanzaio for bundled versions :-)

**Comment by glabmoris** [comment]
Oh my bad ! I judged too quickly upon seeing the npm install \* part

Sounds like I've got some testing to do then ! Thanks a lot !  :)
